### PR TITLE
Initial stab at form fields

### PR DESCRIPTION
**Pull request by jordanwallwork**
Drafted attempt at implementing FormFieldsPerDocument on SignatureRequest (inc. sample usage code in test app)

### CODE REVIEW

**Comment by jordanwallwork** [comment]
(ref #11)

**Comment by BHSPitMonkey** [comment]
Thank you for this. Apologies for the delay so far, but I will need to find some time to review and consider these changes before merging as they're somewhat extensive. I'll be sure to update you when I do.

**Comment by cmpaul** [comment]
@BHSPitMonkey @jordanwallwork This looks reasonable to me. :+1:

**Comment by BHSPitMonkey** [comment]
@jordanwallwork - Your changes have been merged, but I made some adjustments to get it working and to add support for `validation_type`. The main issues were
- The RestSharp JSON serializer not changing C# property names like `apiId` to `api_id` in the JSON as we need, which I "fixed" by changing the property names directly (and breaking convention a little)
- The FormFieldType enum values serializing to integers instead of name strings, which I "fixed" by replacing the enum with string constants (losing a little bit of type safety)

These changes will slightly break any code you've written that uses your new APIs, so be sure to review README.md or the test app source code to see what's changed.

Thanks again for the contribution!

**Comment by jordanwallwork** [comment]
Excellent cheers guys. Regarding the enums, wouldn't the `StringEnumConverter` do what you wanted? You'd simply need to decorate the attribute with `[JsonConverter(typeof(StringEnumConverter))]`

**Pull request merged**
