### PR TITLE
Add optional accessToken parameter

### PR DESCRIPTION
**Pull request by mattoosterbaan**
so that signature request can be sent using oAuth flow

### CODE REVIEW

**Comment by BHSPitMonkey** [comment]
Hi @1michfan! Thanks for this contribution, and sorry it's taken us this long to respond. This functionality has been added in the 1.4.0 Release, which should be getting published to NuGet in the next few days.

To use it, simply call `UseOAuth2Authentication` on a new or existing Client instance:

```c#
var client = new Client();
client.UseOAuth2Authentication("OAUTH ACCESS TOKEN HERE");
// ...
```

Cheers!

**Comment by mattoosterbaan** [comment]
@BHSPitMonkey Thank you for your work! I'm ready to try it out, do you have an ETA for the nuget package?

**Comment by BHSPitMonkey** [comment]
We ran into a hiccup getting the new package hosted on NuGet, but it's being worked on and we'll hopefully have it up later this week. In the meantime, you can download the `.nuget` package directly from the Release page in case it helps:

https://github.com/hellosign/hellosign-dotnet-sdk/releases/tag/v1.4.0

**Comment by mattoosterbaan** [comment]
Ok, cool, I updated my local copy until the NuGet package is released. 
I was able to try it out and am happy to report that the OAuth2 token works as expected.
Thanks again.

**Pull request closed without merging**
