### PR TITLE
Added allow_reassign parameter to the signature request

### PR DESCRIPTION
**Pull request by tommy5dollar**
[#35 - Add support for Allow Reassign](https://github.com/HelloFax/hellosign-dotnet-sdk/issues/35)

### CODE REVIEW

**Comment by BHSPitMonkey** [comment]
Thank you for the PR! One request: we'll need to move your `BaseSignatureRequest.cs` edits to `SignatureRequest.cs` instead, since this parameter is only pertinent to file-based signature requests and cannot be used on template-based ones. (BaseSignatureRequest should only encompass properties and methods common to both.)

Would you be open to making this change on your branch before we merge? Thanks!

**Review by BHSPitMonkey — CHANGES_REQUESTED** [review]
See top-level comment on PR

**Comment by tommy5dollar** [comment]
This should be done now. Let me know if there are any issues and I'll get them fixed ASAP.

**Review by BHSPitMonkey — APPROVED** [review]

**Comment by BHSPitMonkey** [comment]
Thanks @tommy5dollar! We appreciate the patch; Version 0.5.6 should be rolling out to NuGet momentarily with these changes.

**Pull request merged**
